name: homer
description: Clean Book Manager
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  faker: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  image_card: ^0.0.4
  swipeable_tile: ^2.0.0+3
  flutter_bloc: ^8.1.3
  awesome_snackbar_content: ^0.1.3
  equatable: ^2.0.5
  bottom_bar_with_sheet: ^2.4.0
  cached_network_image: ^3.3.0
  material_floating_search_bar_2: ^0.5.0
  banner_listtile: ^2.3.0
  drop_cap_text: ^1.1.3
  event_bus: ^2.0.0
  chip_list: ^2.4.3+8
  multiple_result: ^5.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  vibration: ^1.8.2
  blur: ^3.1.0
  flutter_animate: ^4.2.0+1
  books_finder: ^4.4.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/book-thumbnail-fallback.png
    - assets/book-cover-fallback.webp
    - assets/backup.json
