name: homer
description: Clean Book Manager
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  swipeable_tile: ^2.0.1
  flutter_bloc: ^9.1.0
  awesome_snackbar_content: ^0.1.5
  equatable: ^2.0.7
  bottom_bar_with_sheet: ^2.4.0
  cached_network_image: ^3.4.1
  # TODO: Do something about it - original package is broken on new flutter
  material_floating_search_bar_2:
    path: /home/zbyniu/Projects/material_floating_search_bar/
  banner_listtile: ^2.3.0
  drop_cap_text: ^1.1.3
  chip_list: ^3.1.0
  multiple_result: ^5.2.0
  path_provider: ^2.1.5
  vibration: ^3.1.3
  blur: ^4.0.2
  flutter_animate: ^4.5.2
  books_finder: ^4.4.0
  dartz: ^0.10.1
  flex_color_scheme: ^8.2.0
  flutter_zoom_drawer: ^3.2.0
  day_night_switcher: ^0.2.0+1
  progress_indicators: ^1.0.0
  pull_down_button: ^0.10.2
  another_flutter_splash_screen: ^1.2.1
  lottie: ^3.3.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  share_handler: ^0.0.22
  http: ^1.3.0
  hexcolor: ^3.0.1
  flutter_settings_ui: ^3.0.1
  go_router: ^16.2.4
  shared_preferences: ^2.5.3
  file_picker: ^10.3.3
  share_plus: ^12.0.0
  flutter_multi_slider: ^2.0.1
  fl_chart: ^1.1.1
  collection: ^1.19.1
  event_bus: ^2.0.1
  sentry_flutter: ^9.6.0
  feedback: ^3.1.0
  feedback_sentry: ^3.1.0
  dynamic_color: ^1.7.0
  talker_flutter: ^5.0.1
  talker_bloc_logger: ^5.0.1
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.0
  freezed: ^3.2.3
  flutter_launcher_icons: ^0.14.3
  test: ^1.25.15
  faker: ^2.2.0
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  mutation_test: ^1.7.0
  drift_dev: ^2.28.2
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/book-thumbnail-fallback.png
    - assets/book-cover-fallback.webp
    - assets/splash-screen.json
    - assets/config/
