name: homer
description: Clean Book Manager
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

isar_version: &isar_version 3.1.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  swipeable_tile: ^2.0.1
  flutter_bloc: ^9.1.0
  awesome_snackbar_content: ^0.1.5
  equatable: ^2.0.7
  bottom_bar_with_sheet: ^2.4.0
  cached_network_image: ^3.4.1
  material_floating_search_bar_2: ^0.5.0
  banner_listtile: ^2.3.0
  drop_cap_text: ^1.1.3
  chip_list: ^3.1.0
  multiple_result: ^5.2.0
  # NOTE: https://github.com/isar/isar/issues/1354#issuecomment-1961403185
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  path_provider: ^2.1.5
  vibration: ^3.1.3
  blur: ^4.0.2
  flutter_animate: ^4.5.2
  books_finder: ^4.4.0
  dartz: ^0.10.1
  flex_color_scheme: ^8.2.0
  flutter_zoom_drawer: ^3.2.0
  day_night_switcher: ^0.2.0+1
  progress_indicators: ^1.0.0
  pull_down_button: ^0.10.2
  another_flutter_splash_screen: ^1.2.1
  lottie: ^3.3.1
  json_annotation: ^4.9.0
  share_handler: ^0.0.22
  http: ^1.3.0
  hexcolor: ^3.0.1
  flutter_settings_ui: ^3.0.1
  go_router: ^14.8.1
  shared_preferences: ^2.5.3
  file_picker: ^9.2.3
  share_plus: ^10.1.4
  flutter_multi_slider: ^2.0.1
  fl_chart: ^0.71.0
  collection: ^1.19.1
  event_bus: ^2.0.1
  sentry_flutter: ^9.6.0
  feedback: ^3.1.0
  feedback_sentry: ^3.1.0
  dynamic_color: ^1.7.0
  talker_flutter: ^4.7.6
  talker_bloc_logger: ^4.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.3
  test: ^1.25.15
  faker: ^2.2.0
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  mutation_test: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/book-thumbnail-fallback.png
    - assets/book-cover-fallback.webp
    - assets/homer-backup.json
    - assets/splash-screen.json
    - assets/config/
