// Mocks generated by Mockito 5.4.3 from annotations
// in homer/test/features/manage_books/data/repositories/books_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:homer/features/manage_books/data/datasources/books_data_source.dart'
    as _i2;
import 'package:homer/features/manage_books/data/models/book_dto.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:multiple_result/multiple_result.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BooksDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBooksDataSource extends _i1.Mock implements _i2.BooksDataSource {
  MockBooksDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BookDTO>> getBooks() => (super.noSuchMethod(
        Invocation.method(
          #getBooks,
          [],
        ),
        returnValue: _i3.Future<List<_i4.BookDTO>>.value(<_i4.BookDTO>[]),
      ) as _i3.Future<List<_i4.BookDTO>>);

  @override
  _i3.Future<_i5.Unit> add(_i4.BookDTO? book) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [book],
        ),
        returnValue: _i3.Future<_i5.Unit>.value(_i6.dummyValue<_i5.Unit>(
          this,
          Invocation.method(
            #add,
            [book],
          ),
        )),
      ) as _i3.Future<_i5.Unit>);

  @override
  _i3.Future<_i5.Unit> replaceAll(List<_i4.BookDTO>? books) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAll,
          [books],
        ),
        returnValue: _i3.Future<_i5.Unit>.value(_i6.dummyValue<_i5.Unit>(
          this,
          Invocation.method(
            #replaceAll,
            [books],
          ),
        )),
      ) as _i3.Future<_i5.Unit>);

  @override
  _i3.Future<_i5.Unit> update(_i4.BookDTO? book) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [book],
        ),
        returnValue: _i3.Future<_i5.Unit>.value(_i6.dummyValue<_i5.Unit>(
          this,
          Invocation.method(
            #update,
            [book],
          ),
        )),
      ) as _i3.Future<_i5.Unit>);

  @override
  _i3.Future<_i5.Unit> delete(List<_i4.BookDTO>? bookDTOs) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [bookDTOs],
        ),
        returnValue: _i3.Future<_i5.Unit>.value(_i6.dummyValue<_i5.Unit>(
          this,
          Invocation.method(
            #delete,
            [bookDTOs],
          ),
        )),
      ) as _i3.Future<_i5.Unit>);
}
