// Mocks generated by Mockito 5.4.2 from annotations
// in homer/test/features/backup_and_restore/repositories/local_backup_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:homer/features/backup_and_restore/data/datasources/dante_backup_data_source.dart'
    as _i3;
import 'package:homer/features/backup_and_restore/data/models/dante_backup_dto.dart'
    as _i5;
import 'package:homer/features/backup_and_restore/data/models/local_backup_book_dto.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUnit_0 extends _i1.SmartFake implements _i2.Unit {
  _FakeUnit_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalBackupDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalBackupDataSource extends _i1.Mock
    implements _i3.LocalBackupDataSource {
  MockLocalBackupDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.DanteBackupDTO>> loadDanteAll(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadDanteAll,
          [path],
        ),
        returnValue:
            _i4.Future<List<_i5.DanteBackupDTO>>.value(<_i5.DanteBackupDTO>[]),
      ) as _i4.Future<List<_i5.DanteBackupDTO>>);

  @override
  _i4.Future<List<_i6.LocalBackupBookDTO>> loadAll(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAll,
          [path],
        ),
        returnValue: _i4.Future<List<_i6.LocalBackupBookDTO>>.value(
            <_i6.LocalBackupBookDTO>[]),
      ) as _i4.Future<List<_i6.LocalBackupBookDTO>>);

  @override
  _i4.Future<_i2.Unit> saveAll(
    String? path,
    List<_i6.LocalBackupBookDTO>? books,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAll,
          [
            path,
            books,
          ],
        ),
        returnValue: _i4.Future<_i2.Unit>.value(_FakeUnit_0(
          this,
          Invocation.method(
            #saveAll,
            [
              path,
              books,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Unit>);
}
